os: linux

dist: bionic

python:
    - "3.7"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - build-essential
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
      - pkg-config
      - cryptsetup-bin
  homebrew:
    packages:
      - squashfs
    update: true

sudo: required

before_install:
    - sudo chmod u+x .travis/*.sh
    - "/bin/bash .travis/setup.sh"
    #- wget https://dabdceba-6d04-11e5-ba46-22000b92c6ec.e.globus.org/containers/public/e3sm.sif
    - wget --no-check-certificate https://esgf.anl.gov/monitor/e3sm.sif

script:
    - mkdir $HOME/projects
    - travis_wait 30 singularity exec --hostname singularity -B $HOME/projects e3sm.sif .travis/run.sh
    #- travis_wait 30 ls -la

